namespace Verse;

public enum AltitudeLayer : byte
{
	BelowTerrain = 0,
	TerrainEdges = 1,
	Terrain = 2,
	TerrainScatter = 3,
	Floor = 4,
	Conduits = 5,
	FloorCoverings = 6,
	FloorEmplacement = 7,
	Filth = 8,
	Zone = 9,
	SmallWire = 10,
	LowPlant = 11,
	MoteLow = 12,
	Shadows = 13,
	DoorMoveable = 14,
	Building = 15,
	BuildingBelowTop = 16,
	BuildingOnTop = 17,
	Item = 18,
	ItemImportant = 19,
	LayingPawn = 20,
	PawnRope = 21,
	Projectile = 22,
	Pawn = 23,
	PawnUnused = 24,
	PawnState = 25,
	Blueprint = 26,
	MoteOverheadLow = 27,
	MoteOverhead = 28,
	Gas = 29,
	Skyfaller = 30,
	Weather = 31,
	LightingOverlay = 32,
	VisEffects = 33,
	FogOfWar = 34,
	Darkness = 35,
	WorldClipper = 36,
	Silhouettes = 37,
	MapDataOverlay = 38,
	MetaOverlays = 39,
	_Count = 40
}
